---
bibliography: My Library.bib
csl: style.csl
fontsize: 10pt
geometry: asymmetric
header-includes:
- \usepackage[italian]{babel}
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{float}
- \usepackage{chngcntr}
- \usepackage{amsmath}
- \usepackage{physics}
- \usepackage{textcomp}
- \usepackage{tikz}
- \usetikzlibrary{positioning}
- \onehalfspacing
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \evensidemargin=0in
- \oddsidemargin=0.5in
- \usepackage{fancyhdr}
- \usepackage{listings}
- \lstset{basicstyle=\ttfamily\footnotesize,breaklines=true, aboveskip=\medskipamount}
- \floatplacement{figure}{H}
linestretch: 1.5
link-citations: yes
output:
  pdf_document:
    fig_caption: yes
    fig_height: 3
    fig_width: 5
    number_sections: yes
---
<!-- <script type="text/x-mathjax-config"> -->
<!-- MathJax.Hub.Config({ -->
<!--   TeX: { equationNumbers: { autoNumber: "AMS" } } -->
<!-- }); -->
<!-- </script> -->
```{r child='frontespizio.rmd'}
```
\pagenumbering{gobble}
```{r child='dedica.rmd'}
```
\newpage
\pagenumbering{Roman}
\tableofcontents
\newpage
\listoffigures
\newpage
\listoftables
\cleardoublepage
```{r child='sommario_abstract.rmd'}
```
\newpage
\pagenumbering{arabic}
\pagestyle{fancy}
\fancyhead[LO]{\leftmark}
\fancyhead[RO]{}
\fancyhead[RE]{\rightmark}
\fancyhead[LE]{}
```{r child='introduzione/introduzione.md'}
```
\pagebreak
```{r child='man_dm/man_dm.md'}
```
\pagebreak
```{r child='digital/digital.md'}
```
\pagebreak
```{r child='vim_pred/vim_pred.md'}
```
\pagebreak
```{r child='insight/insight.md'}
```
\pagebreak
```{r child='conclusioni/conclusioni.md'}
```
\pagebreak

# Bibliografia
