---
output: pdf_document
---

# Sommario {-}
L'utilizzo delle tecnologie digitali sta innegabilmente assumendo un ruolo chiave nel progresso tecnologico che, di anno in anno, alza lo standard tecnologico per quanto riguarda le apparecchiature biomedicali. La quantità e la qualità dei dati che vengono generati e scambiati dai dispositivi medici aumentano in modo irrefrenabile e di pari passo si sviluppano le tecnologie di trasferimento di questi dati, offrendo connessioni sempre più veloci, più stabili e sicure. Consce di questa ineluttabile spinta allo sviluppo tecnologico, le aziende produttrici di tecnologie mediche stanno investendo sempre di più nella gestione e nell'analisi di quello che, sicuramente, sarà uno dei massimi protagonisti del prossimo futuro: il dato.

In quest'ottica si inserisce la volontà di utilizzare parte di questa massiva mole di dati per offrire tecnologie mediche più intelligenti, che comunichino preventivamente l'insorgenza di un possibile guasto, diminuendo i rischi per i pazienti e l'onere finanziario delle manutenzioni correttive.

Lo scopo di questa tesi è di indagare le reali possibilità, per l'ASST di Vimercate, di implementare una strategia di manutenzione predittiva sulla base delle tecnologie attualmente presenti in azienda. Il lavoro svolto ha portato allo sviluppo di una web app, destinata al reparto di Endoscopia, per il monitoraggio delle performance di una specifica famiglia di dispositivi medici chiamata lavaendoscopi. Nel software è stato implementato un modulo di manutenzione predittiva che utilizza diversi modelli di previsione per calcolare la probabilità di guasto di queste macchine in un intervallo di tempo di 7 giorni. I modelli predittivi ottenuti, sono stati addestrati con un quantitativo insufficienti di dati e di conseguenza le performance di predizione non hanno raggiunto i risultati sperati. Tuttavia, il software sviluppato ha rappresentato un'innovazione dal punto di vista della gestione delle attività del reparto, in quanto si è riusciti a digitalizzare un importante numero di mansioni che, altrimenti, venivano svolte utilizzando carta e penna, con tutti gli svantaggi associati. Il tool è stato implementato nella rete interna dell'ospedale ed è attualmente in uso presso il reparto.


\newpage

# Abstract {-}
The use of digital technologies is undeniably assuming a key role in the technological progress that, from year to year, raises the technological standard with regard to biomedical equipment. The quantity and quality of data that is generated and exchanged by medical devices increases uncontrollably and at the same time, the technologies for transferring this data develop, offering ever faster, more stable and more secure connections. Aware of this inertia of technological development, the companies producing medical technologies are investing more and more in the management and analysis of what, surely, will be one of the main protagonists of future technological development: the data.

With this in mind is part of the desire to use part of this massive amount of data to offer more intelligent medical technologies, which communicate in advance the onset of a possible failure, reducing the risks for patients and the financial burden of corrective maintenance.

The purpose of this thesis is to investigate the real possibilities, for Vimercate's ASST, of implementing a predictive maintenance strategy based on the technologies currently present in the company. The work carried out led to the development of a web app, intended for the Endoscopy department, to monitor the performance of a specific family of medical devices called an endoscope. The software has implemented a predictive maintenance module that uses different forecasting models to calculate the probability of failure of these machines in a 7-day time interval. The predictive models obtained were trained with insufficient data and consequently the prediction performance did not reach the desired results. However, the software developed has represented an innovation from the point of view of the management of the department's activities, as it has been possible to digitize an important number of tasks that, otherwise, were carried out using paper and pen, with all the associated disadvantages. The tool has been implemented in the hospital's internal network and is currently in use in the department.
